name: repo

on:
  push:
    branches:
      - 'test-*'
      - 'test_*'
      - 'releases/**'

jobs:
  build-packages:
    runs-on: self-hosted
    env:
      ARCH: amd64
      PACKAGE: main/apk-tools 
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Building docker image
        run: |
          docker build -t chimera-cports-builder -f cports.dockerfile
          docker run --rm -v $(pwd):/build chimera-cports-builder

      - name: Uploading packages
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: cports/(packages|key)
          compression-level: 9




